line_style:                   "-"
line_width:                   0.5
marker_style:                 "x"
marker_color:                 "red"
marker_size:                  0.5
plot_time_axis:               true
debug:                        false
feature_of_interest_keys:
  - "coord"
  - "hypothesis"
  - "current"
  - "time"
  - "voltage"
  - "opt_param"
  - "opt_param_err"

available_feature_hypothesis:
  - "uniform"
  - "linear"
  - "exponential"
  - "0"
  - "1"
  - "2"


# Inputs specific to coord_extract.py script
print_coords_to_cli:          true

# Inputs specific to plot_current.py script
range_boundaries:           null
# range_boundaries:           [ [79, 395], [1173, 3906], [8885, 11461], ]